; This file was auto-generated by drush make
core = 7.x

api = 2
api = 2 core = 7.x
projects[] = "drupal"

; Mark-a-Spot Profile
projects[markaspot][type] = profile
projects[markaspot][download][type] = "git"
projects[markaspot][download][url] = "https://github.com/markaspot/markaspot.git"
projects[markaspot][download][branch] = "profile"


; Modules
projects[] = "ctools"
projects[] = "features"
projects[] = "field_group"
projects[] = "field_permissions"
projects[] = "jquery_update"
projects[] = "libraries"
projects[] = "panels"
projects[] = "services"
projects[] = "strongarm"
projects[] = "views"
projects[] = "views_datasource"
; Themes
projects[] = "bootstrap"
projects[] = "rubik"
projects[] = "tao"
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mas][download][type] = ""
projects[mas][download][url] = ""
projects[mas][type] = "theme"

