<?php


/**
 * Implements hook_form_alter().
 */

function markaspot_uuid_form_alter(&$form, &$form_state, $form_id) {
  // Hide the title form field as it is generated via hook_insert
  if ($form_id == 'report_node_form') {
    $form['title']['#type'] = "hidden";
    $form['title']['#required'] = FALSE;
  }
}



/**
 * Generates an universally unique identifier.
 *
 * This function first checks for the PECL alternative for generating
 * universally unique identifiers. If that doesn't exist, then it falls back on
 * PHP for generating that.
 *
 * @return
 *   An UUID, made up of year, month and 8 hex digits.
 * toDo: make this configurable
 */
function markaspot_uuid_generate_uuid() {

  $callback = '_uuid_generate_mas';
  return $callback();
}

function _uuid_generate_mas() {
  // The field names refer to RFC 4122 section 4.1.2.
  return sprintf('%04x%04x',
    // 32 bits for "time_low".
    mt_rand(0, 65535), mt_rand(0, 65535),
    // 16 bits for "time_mid".
    mt_rand(0, 65535)) . "-" . format_date(time(), 'custom', 'ym');
}


/**
 * Implementation of hook_node_insert()
 * Need to update the title field with UUID
 * toDo: make this configurable
 */

function markaspot_uuid_node_insert($node) {

  if ($node->type == 'report' && variable_get('uuid_title') == 1) {


    // Instead of contributed module auto entity_title:
    // get the service name by ID and update the title field

    $tid = $node->field_category[LANGUAGE_NONE][0]['tid'];
    $service = taxonomy_term_load($tid);

    $num_updated = db_update('node')
    ->fields(array(
      'title' => '#' . $node->uuid . " ". $service->name,
    ))
    ->condition('nid', $node->nid, '=')
    ->execute();

    $num_updated = db_update('node_revision')
    ->fields(array(
      'title' => '#' . $node->uuid . " ". $service->name,
    ))
    ->condition('nid', $node->nid, '=')
    ->execute();
  }
}
